// ---------------------------------------------------------------------------
// 沙箱内 SDK 源码与语法自检。
//
// SDK 写在字符串里以免被构建工具包装或改名，注入 iframe 后脚本通过 window.hc
// 使用宿主能力（postMessage 白名单桥）。模块加载时执行一次语法自检。
// ---------------------------------------------------------------------------

/**
 * 沙箱内 SDK。写在字符串里以免被构建工具包装或改名。
 * 只暴露白名单能力；所有调用都是异步 Promise，10 秒无响应即超时。
 */
export const SDK = [
  '(function () {',
  "  'use strict'",
  '  // 先按引用抓住原生 API：脚本随后可能覆盖 window.requestAnimationFrame / String /',
  '  // MutationObserver 等，让运行时探针彻底瘫痪（F-03）。此处早于任何脚本执行，',
  '  // 拿到的必然是原生实现，探针从此不受覆盖影响。',
  '  var nativeRaf = window.requestAnimationFrame',
  '  var nativeSetTimeout = window.setTimeout',
  '  var nativeString = String',
  '  var nativeObserver = window.MutationObserver',
  '  var nativeNow = Date.now',
  '  var pending = new Map()',
  '  var seq = 0',
  '  var listeners = Object.create(null)',
  '  var snapshot = {}',
  '  var cspMeta = document.getElementById("hc-csp")',
  '  var cspContent = cspMeta ? cspMeta.getAttribute("content") : ""',
  '',
  '  function on(name) {',
  '    return function (cb) {',
  '      if (typeof cb !== "function") return function () {}',
  '      if (!listeners[name]) listeners[name] = []',
  '      listeners[name].push(cb)',
  '      return function () {',
  '        var i = listeners[name].indexOf(cb)',
  '        if (i >= 0) listeners[name].splice(i, 1)',
  '      }',
  '    }',
  '  }',
  '',
  '  function emit(name, payload) {',
  '    var arr = listeners[name] || []',
  '    for (var i = 0; i < arr.length; i++) {',
  '      try { arr[i](payload) } catch (e) { console.error("[hc] 回调异常: " + e) }',
  '    }',
  '  }',
  '',
  '  function send(method, params) {',
  '    return new Promise(function (resolve, reject) {',
  '      var id = ++seq',
  '      pending.set(id, { resolve: resolve, reject: reject })',
  '      parent.postMessage({ hc: 1, kind: "call", id: id, method: method, params: params || {} }, "*")',
  '      // 用原生定时器：脚本覆盖 window.setTimeout 也不能让 SDK 的超时保护失效（F-03）。',
  '      nativeSetTimeout(function () {',
  '        if (pending.has(id)) { pending.delete(id); reject(new Error("调用超时：" + method)) }',
  '      }, 10000)',
  '    })',
  '  }',
  '',
  '  function applyTokens(tokens) {',
  '    if (!tokens) return',
  '    var root = document.documentElement',
  '    for (var k in tokens) {',
  '      if (Object.prototype.hasOwnProperty.call(tokens, k)) root.style.setProperty(k, tokens[k])',
  '    }',
  '  }',
  '',
  '  window.addEventListener("message", function (e) {',
  '    var d = e.data',
  '    if (!d || d.hc !== 1) return',
  '    if (d.kind === "result") {',
  '      var p = pending.get(d.id)',
  '      if (!p) return',
  '      pending.delete(d.id)',
  '      if (d.ok) p.resolve(d.data)',
  '      else p.reject(new Error(d.error || "调用失败"))',
  '      return',
  '    }',
  '    if (d.kind === "log") { emit("log", d.data); return }',
  '    if (d.kind === "init" || d.kind === "update") {',
  '      applyTokens(d.data && d.data.tokens)',
  '      snapshot = (d.data && d.data.snapshot) || {}',
  '      emit("update", snapshot)',
  '      return',
  '    }',
  '  })',
  '',
  '  // CSP 看门狗：脚本若移除策略 meta，立即按原内容补回。',
  '  function guard() {',
  '    // 用初始化时抓住的原生观察器：脚本覆盖 window.MutationObserver 会让看门狗失效（F-03）。',
  '    if (!cspContent || typeof nativeObserver !== "function") return',
  '    try {',
  '      var head = document.head || document.documentElement',
  '      new nativeObserver(function () {',
  '        if (document.getElementById("hc-csp")) return',
  '        var m = document.createElement("meta")',
  '        m.id = "hc-csp"',
  '        m.setAttribute("http-equiv", "Content-Security-Policy")',
  '        m.setAttribute("content", cspContent)',
  '        head.insertBefore(m, head.firstChild)',
  '      }).observe(document.documentElement, { childList: true, subtree: true })',
  '    } catch (e) {}',
  '  }',
  '',
  '  // ---- 3D 玩家模型容器（可选能力） ----',
  '  // 在脚本自己的 DOM 里构建纯 CSS 3D 模型：主页可自定义尺寸（size），自带缓慢自转与拖动旋转。',
  '  // 皮肤 / 披风贴图由宿主经 model3d.skin 提供（离线账号 / 未设置皮肤时为空，模型显示占位）。',
  '  var M3D_UV = {',
  '    head: { front: [8, 8, 8, 8], back: [24, 8, 8, 8], right: [0, 8, 8, 8], left: [16, 8, 8, 8], top: [8, 0, 8, 8], bottom: [16, 0, 8, 8] },',
  '    hat: { front: [40, 8, 8, 8], back: [56, 8, 8, 8], right: [32, 8, 8, 8], left: [48, 8, 8, 8], top: [40, 0, 8, 8], bottom: [48, 0, 8, 8] },',
  '    torso: { front: [20, 20, 8, 12], back: [32, 20, 8, 12], right: [16, 20, 4, 12], left: [28, 20, 4, 12], top: [20, 16, 8, 4], bottom: [28, 16, 8, 4] },',
  '    jacket: { front: [20, 36, 8, 12], back: [32, 36, 8, 12], right: [16, 36, 4, 12], left: [28, 36, 4, 12], top: [20, 32, 8, 4], bottom: [28, 32, 8, 4] },',
  '    rArm: { front: [44, 20, 4, 12], back: [52, 20, 4, 12], right: [40, 20, 4, 12], left: [48, 20, 4, 12], top: [44, 16, 4, 4], bottom: [48, 16, 4, 4] },',
  '    lArm: { front: [36, 52, 4, 12], back: [44, 52, 4, 12], right: [32, 52, 4, 12], left: [40, 52, 4, 12], top: [36, 48, 4, 4], bottom: [40, 48, 4, 4] },',
  '    rArmSlim: { front: [44, 20, 3, 12], back: [51, 20, 3, 12], right: [40, 20, 4, 12], left: [47, 20, 4, 12], top: [44, 16, 3, 4], bottom: [47, 16, 3, 4] },',
  '    lArmSlim: { front: [36, 52, 3, 12], back: [43, 52, 3, 12], right: [32, 52, 4, 12], left: [39, 52, 4, 12], top: [36, 48, 3, 4], bottom: [39, 48, 3, 4] },',
  '    rLeg: { front: [4, 20, 4, 12], back: [12, 20, 4, 12], right: [0, 20, 4, 12], left: [8, 20, 4, 12], top: [4, 16, 4, 4], bottom: [8, 16, 4, 4] },',
  '    lLeg: { front: [20, 52, 4, 12], back: [28, 52, 4, 12], right: [16, 52, 4, 12], left: [24, 52, 4, 12], top: [20, 48, 4, 4], bottom: [24, 48, 4, 4] },',
  '    cape: { front: [12, 1, 10, 16], back: [1, 1, 10, 16], right: [0, 1, 1, 16], left: [11, 1, 1, 16], top: [1, 0, 10, 1], bottom: [11, 0, 10, 1] }',
  '  }',
  '',
  '  function m3dEl(tag, css, parent) {',
  '    var el = document.createElement(tag)',
  '    if (css) el.style.cssText = css',
  '    if (parent) parent.appendChild(el)',
  '    return el',
  '  }',
  '',
  '  function m3dBox(parent, src, unit, skinH, w, h, d, uv, mirror) {',
  '    var box = m3dEl("div", "position:absolute;width:" + w + "px;height:" + h + "px;transform-style:preserve-3d", parent)',
  '    function face(r, bw, bh, ox, oy, tf) {',
  '      m3dEl("div",',
  '        "position:absolute;width:" + bw + "px;height:" + bh + "px;left:" + ox + "px;top:" + oy + "px;" +',
  '        "background-image:url(\\"" + src + "\\");background-size:" + (64 * unit) + "px " + (skinH * unit) + "px;" +',
  '        "background-position:" + (-r[0] * unit) + "px " + (-r[1] * unit) + "px;background-repeat:no-repeat;" +',
  '        "image-rendering:pixelated;backface-visibility:hidden;transform:" + (mirror ? "scaleX(-1) " : "") + tf, box)',
  '    }',
  '    face(uv.front, w, h, 0, 0, "translateZ(" + (d / 2) + "px)")',
  '    face(uv.back, w, h, 0, 0, "rotateY(180deg) translateZ(" + (d / 2) + "px)")',
  '    face(uv.right, d, h, (w - d) / 2, 0, "rotateY(90deg) translateZ(" + (w / 2) + "px)")',
  '    face(uv.left, d, h, (w - d) / 2, 0, "rotateY(-90deg) translateZ(" + (w / 2) + "px)")',
  '    face(uv.top, w, d, 0, (h - d) / 2, "rotateX(90deg) translateZ(" + (h / 2) + "px)")',
  '    face(uv.bottom, w, d, 0, (h - d) / 2, "rotateX(-90deg) translateZ(" + (h / 2) + "px)")',
  '    return box',
  '  }',
  '',
  '  function m3dStyle() {',
  '    if (document.getElementById("hc-model3d-style")) return',
  '    var st = document.createElement("style")',
  '    st.id = "hc-model3d-style"',
  '    st.textContent = "@keyframes hc-model3d-spin{from{transform:rotateX(-8deg) rotateY(0deg)}to{transform:rotateX(-8deg) rotateY(360deg)}}"',
  '    ;(document.head || document.documentElement).appendChild(st)',
  '  }',
  '',
  '  function mountModel3D(target, options) {',
  '    options = options || {}',
  '    var host = typeof target === "string" ? document.querySelector(target) : target',
  '    if (!host) throw new Error("model3d.mount：找不到目标元素（" + String(target) + "）")',
  '    m3dStyle()',
  '    var size = Number(options.size)',
  '    if (!isFinite(size) || size <= 0) size = 200',
  '    size = Math.max(40, Math.min(1024, size))',
  '    var autoSpin = options.autoSpin !== false',
  '    var draggable = options.draggable !== false',
  '    var showCape = options.showCape !== false',
  '    var root = m3dEl("div", "", host)',
  '    root.className = "hc-model3d"',
  '    var data = null, skinH = 64, destroyed = false',
  '    var rot = { x: 0, y: 0 }, drag = null, stage = null, spin = null',
  '',
  '    function onDown(e) {',
  '      if (e.button !== 0 && e.pointerType === "mouse") return',
  '      try { stage.setPointerCapture(e.pointerId) } catch (_) {}',
  '      drag = { x: e.clientX, y: e.clientY, rx: rot.x, ry: rot.y }',
  '      stage.style.cursor = "grabbing"',
  '      if (autoSpin && spin) spin.style.animationPlayState = "paused"',
  '    }',
  '    function onMove(e) {',
  '      if (!drag) return',
  '      rot.x = Math.max(-89, Math.min(89, drag.rx - (e.clientY - drag.y) * 0.5))',
  '      rot.y = drag.ry + (e.clientX - drag.x) * 0.5',
  '      stage.style.transform = "rotateX(" + rot.x + "deg) rotateY(" + rot.y + "deg)"',
  '    }',
  '    function onUp(e) {',
  '      if (!drag) return',
  '      drag = null',
  '      stage.style.cursor = draggable ? "grab" : "default"',
  '      if (autoSpin && spin) spin.style.animationPlayState = "running"',
  '      try { if (stage.hasPointerCapture(e.pointerId)) stage.releasePointerCapture(e.pointerId) } catch (_) {}',
  '    }',
  '',
  '    function render() {',
  '      if (destroyed) return',
  '      root.innerHTML = ""',
  '      root.style.cssText = ""',
  '      if (!data || !data.skinUrl) {',
  '        var ph = m3dEl("div", "width:" + size + "px;height:" + size + "px;display:flex;align-items:center;justify-content:center;font-size:12px;color:var(--hc-text-tertiary,#888)", root)',
  '        ph.textContent = "暂无皮肤（离线账号或未设置皮肤）"',
  '        return',
  '      }',
  '      var unit = size / 34',
  '      var u = function (n) { return n * unit }',
  '      var legacy = skinH === 32',
  '      var slimArm = data.skinModel === "slim" && !legacy',
  '      var capeSrc = showCape ? (data.capeUrl || "") : ""',
  '      root.style.cssText = "position:relative;width:" + size + "px;height:" + size + "px;perspective:" + (size * 4) + "px;display:flex;align-items:center;justify-content:center"',
  '      stage = m3dEl("div", "position:relative;width:" + u(16) + "px;height:" + u(32) + "px;transform-style:preserve-3d;transform:rotateX(0deg) rotateY(0deg);cursor:" + (draggable ? "grab" : "default") + ";touch-action:none;user-select:none", root)',
  '      spin = m3dEl("div", "position:absolute;inset:0;transform-style:preserve-3d" + (autoSpin ? ";animation:hc-model3d-spin 18s linear infinite" : ""), stage)',
  '      var head = m3dEl("div", "position:absolute;left:" + u(4) + "px;top:0;transform-style:preserve-3d", spin)',
  '      m3dBox(head, data.skinUrl, unit, skinH, u(8), u(8), u(8), M3D_UV.head, false)',
  '      var hat = m3dEl("div", "position:absolute;left:" + u(-0.5) + "px;top:" + u(-0.5) + "px;transform-style:preserve-3d", head)',
  '      m3dBox(hat, data.skinUrl, unit, skinH, u(9), u(9), u(9), M3D_UV.hat, false)',
  '      var torso = m3dEl("div", "position:absolute;left:" + u(4) + "px;top:" + u(8) + "px;transform-style:preserve-3d", spin)',
  '      m3dBox(torso, data.skinUrl, unit, skinH, u(8), u(12), u(4), M3D_UV.torso, false)',
  '      if (!legacy) {',
  '        var jacket = m3dEl("div", "position:absolute;left:" + u(-0.25) + "px;top:" + u(-0.25) + "px;transform-style:preserve-3d", torso)',
  '        m3dBox(jacket, data.skinUrl, unit, skinH, u(8.5), u(12.5), u(4.5), M3D_UV.jacket, false)',
  '      }',
  '      var rArm = m3dEl("div", "position:absolute;left:" + u(slimArm ? 1 : 0) + "px;top:" + u(8) + "px;transform-style:preserve-3d", spin)',
  '      m3dBox(rArm, data.skinUrl, unit, skinH, u(slimArm ? 3 : 4), u(12), u(4), slimArm ? M3D_UV.rArmSlim : M3D_UV.rArm, false)',
  '      var lArm = m3dEl("div", "position:absolute;left:" + u(12) + "px;top:" + u(8) + "px;transform-style:preserve-3d", spin)',
  '      m3dBox(lArm, data.skinUrl, unit, skinH, u(slimArm ? 3 : 4), u(12), u(4), legacy ? M3D_UV.rArm : (slimArm ? M3D_UV.lArmSlim : M3D_UV.lArm), legacy)',
  '      var rLeg = m3dEl("div", "position:absolute;left:" + u(4) + "px;top:" + u(20) + "px;transform-style:preserve-3d", spin)',
  '      m3dBox(rLeg, data.skinUrl, unit, skinH, u(4), u(12), u(4), M3D_UV.rLeg, false)',
  '      var lLeg = m3dEl("div", "position:absolute;left:" + u(8) + "px;top:" + u(20) + "px;transform-style:preserve-3d", spin)',
  '      m3dBox(lLeg, data.skinUrl, unit, skinH, u(4), u(12), u(4), legacy ? M3D_UV.rLeg : M3D_UV.lLeg, legacy)',
  '      if (capeSrc) {',
  '        var capeEl = m3dEl("div", "position:absolute;left:" + u(3) + "px;top:" + u(8) + "px;transform-style:preserve-3d;transform:translateZ(" + (-2.5 * unit) + "px)", spin)',
  '        m3dBox(capeEl, capeSrc, unit, 32, u(10), u(16), u(1), M3D_UV.cape, false)',
  '      }',
  '      if (draggable) {',
  '        stage.addEventListener("pointerdown", onDown)',
  '        stage.addEventListener("pointermove", onMove)',
  '        stage.addEventListener("pointerup", onUp)',
  '        stage.addEventListener("pointercancel", onUp)',
  '      }',
  '    }',
  '',
  '    function load() {',
  '      send("model3d.skin").then(function (d) {',
  '        if (destroyed) return',
  '        data = d || null',
  '        if (!data || !data.skinUrl) { render(); return }',
  '        var probeImg = new Image()',
  '        probeImg.onload = function () { if (!destroyed) { skinH = probeImg.naturalHeight === 32 ? 32 : 64; render() } }',
  '        probeImg.onerror = function () { if (!destroyed) { skinH = 64; render() } }',
  '        probeImg.src = data.skinUrl',
  '      }, function () { if (!destroyed) { data = null; render() } })',
  '    }',
  '',
  '    var ctrl = {',
  '      el: root,',
  '      setSize: function (n) {',
  '        var v = Number(n)',
  '        if (!isFinite(v) || v <= 0) return size',
  '        size = Math.max(40, Math.min(1024, v))',
  '        rot = { x: 0, y: 0 }',
  '        drag = null',
  '        render()',
  '        return size',
  '      },',
  '      refresh: function () { load(); return ctrl },',
  '      destroy: function () { destroyed = true; if (root.parentNode) root.parentNode.removeChild(root) }',
  '    }',
  '    load()',
  '    return ctrl',
  '  }',
  '',
  '  var api = {',
  '    version: "1.0",',
  '    onReady: on("ready"),',
  '    onUpdate: on("update"),',
  '    onLog: on("log"),',
  '    state: function () { return snapshot },',
  '    system: { memory: function () { return send("system.memory") } },',
  '    settings: {',
  '      memory: {',
  '        get: function () { return send("settings.memory.get") },',
  '        set: function (mb) { return send("settings.memory.set", { memoryMb: mb }) }',
  '      }',
  '    },',
  '    account: {',
  '      current: function () { return send("account.current") },',
  '      avatar: function () { return send("account.avatar") }',
  '    },',
  '    versions: {',
  '      list: function () { return send("versions.list") },',
  '      selected: function () { return send("versions.selected") },',
  '      select: function (id) { return send("versions.select", { id: id }) },',
  '      info: function () { return send("versions.info") },',
  '      loader: function () { return send("versions.loader") },',
  '      number: function () { return send("versions.number") }',
  '    },',
  '    versionDirs: {',
  '      list: function () { return send("versiondirs.list") },',
  '      selected: function () { return send("versiondirs.selected") },',
  '      select: function (id) { return send("versiondirs.select", { id: id }) }',
  '    },',
  '    launcher: { version: function () { return send("launcher.version") } },',
  '    game: {',
  '      launch: function () { return send("game.launch") },',
  '      stop: function () { return send("game.stop") },',
  '      state: function () { return send("game.state") }',
  '    },',
  '    log: {',
  '      info: function (m) { return send("log.write", { level: "info", message: String(m) }) },',
  '      warn: function (m) { return send("log.write", { level: "warn", message: String(m) }) },',
  '      error: function (m) { return send("log.write", { level: "error", message: String(m) }) }',
  '    },',
  '    theme: { get: function () { return send("theme.get") } },',
  '    model3d: {',
  '      skin: function () { return send("model3d.skin") },',
  '      mount: function (target, options) { return mountModel3D(target, options) }',
  '    },',
  '    openExternal: function (url) { return send("shell.openExternal", { url: url }) }',
  '  }',
  '',
  '  try {',
  '    Object.defineProperty(window, "hc", { value: api, writable: false, configurable: false })',
  '  } catch (e) { window.hc = api }',
  '',
  '  // ---- 运行时安全探针 ----',
  '  // 每个「新加载进来的元素」与「动态写入/执行的源码」都要交给宿主检查：',
  '  // 脚本可以用字符串拼接绕过静态匹配，只能在运行时按实际发生的行为再查一遍。',
  '  var probeQueue = []',
  '  var probeChars = 0',
  '  var probeScheduled = false',
  '  var probeDropped = false',
  '  var PROBE_MAX_ITEMS = 20000',
  '  var PROBE_MAX_CHARS = 1000000',
  '  // 短时间内的元素插入速率：脚本可能一次性插入海量元素，把危险载荷挤出探针队列（F-06 / B07）。',
  '  // 队列长度会被逐帧排空，单看队列会漏判，所以要额外按「每秒插入量」判断。',
  '  var burstCount = 0',
  '  var burstAt = 0',
  '  var PROBE_BURST_MAX = 20000',
  '',
  '  function countInsert() {',
  '    var now = nativeNow()',
  '    if (now - burstAt > 1000) { burstAt = now; burstCount = 0 }',
  '    burstCount++',
  '    if (burstCount > PROBE_BURST_MAX) {',
  '      // 达标即刻预约上报：离屏洪水不经过 MutationObserver，探针队列可能一直是空的，',
  '      // 不能再指望 probe() 来触发 flushProbe，否则 element-flood 永远发不出去（F-06 / B07）。',
  '      probeDropped = true',
  '      scheduleProbe()',
  '    }',
  '  }',
  '',
  '  function scheduleProbe() {',
  '    if (probeScheduled) return',
  '    probeScheduled = true',
  '    // 用初始化时抓住的原生引用：脚本覆盖 window.requestAnimationFrame 也瘫痪不了探针（F-03 / B02）。',
  '    if (typeof nativeRaf === "function") nativeRaf(flushProbe)',
  '    else nativeSetTimeout(flushProbe, 16)',
  '  }',
  '',
  '  function flushProbe() {',
  '    probeScheduled = false',
  '    // 队列空但已判定洪水时也要上报：element-flood 是 fail-closed 信号，不能被早退吞掉（B07）。',
  '    if (!probeQueue.length && !probeDropped) return',
  '    var batch = probeQueue.splice(0, 200)',
  '    for (var k = 0; k < batch.length; k++) probeChars -= batch[k].text.length',
  '    if (probeDropped) { probeDropped = false; batch.push({ where: "element-flood", text: "" }) }',
  '    if (probeQueue.length) scheduleProbe()',
  '    parent.postMessage({ hc: 1, kind: "probe", batch: batch }, "*")',
  '  }',
  '',
  '  function probe(where, text) {',
  '    if (text === null || text === undefined) return',
  '    // 用原生 String：脚本覆盖 window.String 让探针把内容转成空串以躲过检查（F-03 / B03）。',
  '    var s = nativeString(text)',
  '    if (!s) return',
  '    // 不再对单条做 8000 字符截断：截断后危险关键字可能落在被砍掉的部分，',
  '    // 只要把载荷塞到超长注释之后即可漏检（F-01 / B01）。容量由累计上限兜底。',
  '    if (probeQueue.length >= PROBE_MAX_ITEMS || probeChars >= PROBE_MAX_CHARS) {',
  '      probeDropped = true',
  '      return',
  '    }',
  '    probeQueue.push({ where: where, text: s })',
  '    probeChars += s.length',
  '    scheduleProbe()',
  '  }',
  '',
  '  // 需要观察「属性后改」的属性：脚本常先插入一个干净元素，之后再赋值 src / href（F-06 / B04 / B05）。',
  '  var URL_ATTRS = ["src", "href", "xlink:href", "action", "formaction", "poster", "data", "background", "cite", "ping", "srcset", "manifest", "longdesc"]',
  '  var ATTR_FILTER = ["src", "href", "xlink:href", "action", "formaction", "poster", "data", "background", "cite", "ping", "srcset", "manifest", "longdesc", "style", "srcdoc", "http-equiv", "content"]',
  '',
  '  // 只认 http(s):// 与 // 开头的真正外链；data: / blob: / 相对路径 / #锚点都不算。',
  '  function isExternalUrl(u) {',
  '    var s = nativeString(u).trim()',
  '    if (!s) return false',
  '    if (/^(?:data|blob|file|about|javascript|mailto|tel):/i.test(s)) return false',
  '    if (s.charAt(0) === "#") return false',
  '    return /^(?:https?:)?\\/\\//i.test(s)',
  '  }',
  '',
  '  // 外部资源 / 导航地址：交给宿主按「是否已授权联网」判断（B04 / B05）；',
  '  // javascript: 伪协议直接标记为伪装代码。',
  '  function probeUrl(where, url) {',
  '    if (url === null || url === undefined) return',
  '    var s = nativeString(url).trim()',
  '    if (!s) return',
  '    if (/^javascript:/i.test(s)) { probe("element:" + where + "#javascript", s); return }',
  '    if (/^(?:data|blob):/i.test(s)) return',
  '    if (isExternalUrl(s)) probe("net:" + where, s)',
  '  }',
  '',
  '  // CSS 里的 url(...)：外部地址按联网事件上报，是隐蔽信标的常用手法（F-06 / B09）。',
  '  function probeCss(text) {',
  '    var css = nativeString(text)',
  '    if (!css) return',
  '    if (css.length > 20000) css = css.slice(0, 20000)',
  '    var re = /url\\(\\s*["\']?([^"\')]+)["\']?\\s*\\)/gi',
  '    var m',
  '    while ((m = re.exec(css)) !== null) {',
  '      if (isExternalUrl(m[1])) probe("net:css", m[1].trim())',
  '    }',
  '  }',
  '',
  '  // 摘掉 <meta http-equiv="refresh">（F-05 / D01）：meta refresh 能让沙箱「自我导航」，',
  '  // 把拼接出的数据带出去，这条通路不受 connect-src 管辖，必须在生效「前」就地消灭。',
  '  // 立即改写 http-equiv 使其失效；再从 DOM 移除。改属性会再触发一次 attributes 记录，',
  '  // 但那时 http-equiv 已不是 refresh，函数会直接返回，不会自激。',
  '  function defuseMetaRefresh(el) {',
  '    var eq = ""',
  '    try { eq = (el.getAttribute("http-equiv") || "").toLowerCase() } catch (e) { eq = "" }',
  '    if (eq !== "refresh") return',
  '    try { if (el.setAttribute) el.setAttribute("http-equiv", "x-hc-defused") } catch (e) {}',
  '    try { if (el.removeAttribute) el.removeAttribute("content") } catch (e) {}',
  '    var drop = function () {',
  '      try { if (el.parentNode) el.parentNode.removeChild(el) } catch (e) {}',
  '    }',
  '    if (typeof nativeSetTimeout === "function") nativeSetTimeout(drop, 0)',
  '    else drop()',
  '  }',
  '',
  '  // 元素本体：先查 URL 属性（外链按联网上报），再按标签补充正文。',
  '  function probeElement(el) {',
  '    var tag = el.tagName ? nativeString(el.tagName).toUpperCase() : ""',
  '    var hasAttr = true',
  '    try { hasAttr = !el.attributes || el.attributes.length > 0 } catch (e) { hasAttr = true }',
  '    if (hasAttr) {',
  '      for (var i = 0; i < URL_ATTRS.length; i++) {',
  '        var a = URL_ATTRS[i]',
  '        var v = null',
  '        try { v = el.getAttribute ? el.getAttribute(a) : null } catch (e) { v = null }',
  '        if (v) probeUrl(tag.toLowerCase() + ":" + a, v)',
  '      }',
  '      var cv = null',
  '      try { cv = el.getAttribute ? el.getAttribute("srcdoc") : null } catch (e) { cv = null }',
  '      if (cv) probe("element:" + tag.toLowerCase() + ":srcdoc", cv)',
  '      var st = null',
  '      try { st = el.getAttribute ? el.getAttribute("style") : null } catch (e) { st = null }',
  '      if (st) probeCss(st)',
  '    }',
  '    if (tag === "SCRIPT") {',
  '      var src = ""',
  '      try { src = el.getAttribute("src") || "" } catch (e) { src = "" }',
  '      if (!src) probe("element:script:inline", el.textContent || "")',
  '      return',
  '    }',
  '    if (tag === "STYLE") {',
  '      var css = el.textContent || ""',
  '      probeCss(css)',
  '      probe("element:style", css)',
  '      return',
  '    }',
  '    if (tag === "TEMPLATE") { probe("element:template", el.innerHTML || ""); return }',
  '    if (tag === "META") {',
  '      var eq = ""',
  '      try { eq = (el.getAttribute("http-equiv") || "").toLowerCase() } catch (e) { eq = "" }',
  '      if (eq === "refresh") {',
  '        var c = ""',
  '        try { c = el.getAttribute("content") || "" } catch (e) { c = "" }',
  '        var um = /url\\s*=\\s*([^;\\s]+)/i.exec(c)',
  '        if (um) probeUrl("meta:refresh", um[1])',
  '        // 先上报再摘除：导航必须在这条 meta 生效前被消灭（F-05 / D01）。',
  '        defuseMetaRefresh(el)',
  '      }',
  '    }',
  '  }',
  '',
  '  // 递归遍历新增子树：文本节点也要查（createTextNode 注入危险内容，F-06 / B03 / B08）。',
  '  function probeSubtree(n) {',
  '    if (!n) return',
  '    if (n.nodeType === 3) { probe("text", n.data || n.nodeValue || ""); return }',
  '    if (n.nodeType !== 1) return',
  '    countInsert()',
  '    probeElement(n)',
  '    var kids = n.childNodes',
  '    if (!kids) return',
  '    for (var i = 0; i < kids.length; i++) probeSubtree(kids[i])',
  '  }',
  '',
  '  function watch() {',
  '    if (typeof nativeObserver === "function") {',
  '      try {',
  '        new nativeObserver(function (records) {',
  '          for (var i = 0; i < records.length; i++) {',
  '            var rec = records[i]',
  '            if (rec.type === "attributes") {',
  '              var an = rec.attributeName',
  '              var target = rec.target',
  '              var av = null',
  '              try { av = target.getAttribute ? target.getAttribute(an) : null } catch (e) { av = null }',
  '              if (!av) continue',
  '              if (an === "style") { probeCss(av); continue }',
  '              if (an === "srcdoc") { probe("element:iframe:srcdoc", av); continue }',
  '              var t = target.tagName ? nativeString(target.tagName).toLowerCase() : "element"',
  '              probeUrl(t + ":" + an, av)',
  '              // 先插一个干净的 meta，之后再改 http-equiv / content 造出 refresh 也要摘掉（F-05 / D01）。',
  '              if (t === "meta") defuseMetaRefresh(target)',
  '              continue',
  '            }',
  '            var added = rec.addedNodes',
  '            if (!added) continue',
  '            for (var j = 0; j < added.length; j++) probeSubtree(added[j])',
  '          }',
  '        }).observe(document.documentElement, {',
  '          childList: true,',
  '          subtree: true,',
  '          attributes: true,',
  '          attributeFilter: ATTR_FILTER',
  '        })',
  '      } catch (e) {}',
  '    }',
  '    // write / writeln 会把整页重写并按字符串注入内容。探针本身会被探针队列截断，',
  '    // 所以「是否含脚本/事件处理器」在沙箱内按完整字符串判定，再用 # 标记回传（F-10）。',
  '    var writeInject = function (s) {',
  '      var str = s === null || s === undefined ? "" : nativeString(s)',
  '      var flags = []',
  '      if (/<script[\\s>]/i.test(str)) flags.push("script")',
  '      if (/<iframe[\\s>]/i.test(str)) flags.push("iframe")',
  '      if (/\\son[a-z]+\\s*=/i.test(str)) flags.push("handler")',
  '      if (/javascript:/i.test(str)) flags.push("javascript")',
  '      return flags',
  '    }',
  '    try {',
  '      var rawWrite = document.write',
  '      if (typeof rawWrite === "function") {',
  '        document.write = function (s) {',
  '          var f = writeInject(s)',
  '          probe("document.write" + (f.length ? "#" + f.join(",") : ""), s)',
  '          return rawWrite.apply(document, arguments)',
  '        }',
  '      }',
  '    } catch (e) {}',
  '    try {',
  '      var rawWriteln = document.writeln',
  '      if (typeof rawWriteln === "function") {',
  '        document.writeln = function (s) {',
  '          var f = writeInject(s)',
  '          probe("document.writeln" + (f.length ? "#" + f.join(",") : ""), s)',
  '          return rawWriteln.apply(document, arguments)',
  '        }',
  '      }',
  '    } catch (e) {}',
  '    try {',
  '      var rawEval = window.eval',
  '      if (typeof rawEval === "function") {',
  '        window.eval = function (s) { probe("eval", s); return rawEval.apply(window, arguments) }',
  '      }',
  '    } catch (e) {}',
  '    var wrapTimer = function (name) {',
  '      var raw = window[name]',
  '      if (typeof raw !== "function") return',
  '      window[name] = function (fn) {',
  '        if (typeof fn === "string") probe(name + ":string", fn)',
  '        return raw.apply(window, arguments)',
  '      }',
  '    }',
  '    wrapTimer("setTimeout")',
  '    wrapTimer("setInterval")',
  '',
  '    // 元素创建洪水：脚本可以把海量节点建进离屏的 DocumentFragment，再在 setTimeout 之前',
  '    // 同步 appendChild（此刻 fragment 还是空的）——节点永远不进实时 DOM，MutationObserver',
  '    // 与插入计数都看不到。故在 createElement/createElementNS 上按「创建量/秒」直接计数，',
  '    // 创建即算，堵住这条离屏洪水通道（F-06 / B07）。',
  '    var wrapCreate = function (name) {',
  '      try {',
  '        var raw = document[name]',
  '        if (typeof raw !== "function") return',
  '        document[name] = function () {',
  '          countInsert()',
  '          return raw.apply(document, arguments)',
  '        }',
  '      } catch (e) {}',
  '    }',
  '    wrapCreate("createElement")',
  '    wrapCreate("createElementNS")',
  '',
  '    // ---- 运行时网络探针 ----',
  '    // CSP 的 connect-src 是兜底；这里再主动上报「实际发起的外部请求」的地址，',
  '    // 由宿主判断该脚本是否已获准联网 —— 拼接/模板构造出的地址静态收集不到（F-08）。',
  '    var wrapNet = function (name, where) {',
  '      var Ctor = window[name]',
  '      if (typeof Ctor !== "function") return',
  '      var wrapped = function (url) {',
  '        try { probe(where, url) } catch (e) {}',
  '        var args = [].slice.call(arguments)',
  '        if (window.Reflect && window.Reflect.construct) return window.Reflect.construct(Ctor, args)',
  '        var o = Object.create(Ctor.prototype)',
  '        Ctor.apply(o, args)',
  '        return o',
  '      }',
  '      try { window[name] = wrapped } catch (e) {}',
  '    }',
  '    try {',
  '      var rawFetch = window.fetch',
  '      if (typeof rawFetch === "function") {',
  '        window.fetch = function (input) {',
  '          try { probe("net:fetch", input && input.url ? input.url : input) } catch (e) {}',
  '          return rawFetch.apply(window, arguments)',
  '        }',
  '      }',
  '    } catch (e) {}',
  '    try {',
  '      var xhrProto = window.XMLHttpRequest && window.XMLHttpRequest.prototype',
  '      var rawOpen = xhrProto && xhrProto.open',
  '      if (typeof rawOpen === "function") {',
  '        xhrProto.open = function (method, url) {',
  '          try { probe("net:xhr", url) } catch (e) {}',
  '          return rawOpen.apply(this, arguments)',
  '        }',
  '      }',
  '    } catch (e) {}',
  '    wrapNet("WebSocket", "net:websocket")',
  '    wrapNet("EventSource", "net:sse")',
  '    // ---- WebRTC 探针（D08）：RTCPeerConnection 完全绕过 connect-src，可借 STUN 泄露内网',
  '    // 地址、借 data channel 外发数据。任何构造都按「隐蔽通道」上报，由宿主一律封锁。',
  '    try {',
  '      var RawRTC = window.RTCPeerConnection || window.webkitRTCPeerConnection',
  '      if (typeof RawRTC === "function") {',
  '        var wrapRtc = function (Ctor) {',
  '          var Wrapped = function (cfg) {',
  '            var urls = []',
  '            try {',
  '              var servers = cfg && cfg.iceServers',
  '              if (servers && servers.length) {',
  '                for (var i = 0; i < servers.length; i++) {',
  '                  var s = servers[i] || {}',
  '                  var u = s.urls',
  '                  if (typeof u === "string") urls.push(u)',
  '                  else if (u && u.length) { for (var j = 0; j < u.length; j++) urls.push(nativeString(u[j])) }',
  '                }',
  '              }',
  '            } catch (e) {}',
  '            try { probe("danger:webrtc", "RTCPeerConnection" + (urls.length ? " iceServers=" + urls.join(",") : "")) } catch (e) {}',
  '            if (window.Reflect && window.Reflect.construct) return window.Reflect.construct(Ctor, [].slice.call(arguments))',
  '            return new Ctor(cfg)',
  '          }',
  '          try { Wrapped.prototype = Ctor.prototype } catch (e) {}',
  '          return Wrapped',
  '        }',
  '        var RtcWrapped = wrapRtc(RawRTC)',
  '        try { window.RTCPeerConnection = RtcWrapped } catch (e) {}',
  '        try { if (window.webkitRTCPeerConnection) window.webkitRTCPeerConnection = RtcWrapped } catch (e) {}',
  '      }',
  '    } catch (e) {}',
  '    try {',
  '      if (navigator && typeof navigator.sendBeacon === "function") {',
  '        var rawBeacon = navigator.sendBeacon',
  '        navigator.sendBeacon = function (url) {',
  '          try { probe("net:beacon", url) } catch (e) {}',
  '          return rawBeacon.apply(navigator, arguments)',
  '        }',
  '      }',
  '    } catch (e) {}',
  '  }',
  '',
  '  guard()',
  '  watch()',
  '  // 光标光晕跟随：鼠标在 iframe 内时宿主收不到 mousemove，光晕会定格在进入前的位置。',
  '  // 这里把 iframe 内的坐标回传，宿主换算成窗口坐标后驱动光晕。仅坐标，不含脚本内容。',
  '  // 每帧最多回传一次，避免高频 mousemove 产生大量 postMessage。',
  '  try {',
  '    var cursorPending = false',
  '    var cursorX = 0',
  '    var cursorY = 0',
  '    var flushCursor = function () {',
  '      cursorPending = false',
  '      parent.postMessage({ hc: 1, kind: "cursor", x: cursorX, y: cursorY }, "*")',
  '    }',
  '    document.addEventListener("mousemove", function (e) {',
  '      cursorX = e.clientX',
  '      cursorY = e.clientY',
  '      if (cursorPending) return',
  '      cursorPending = true',
  '      if (typeof nativeRaf === "function") nativeRaf(flushCursor)',
  '      else nativeSetTimeout(flushCursor, 16)',
  '    }, { passive: true })',
  '  } catch (e) {}',
  '  parent.postMessage({ hc: 1, kind: "hello" }, "*")',
  '  emit("ready", snapshot)',
  '})()'
].join('\n')

/**
 * SDK 语法自检（模块加载时执行一次）。
 *
 * SDK 是字符串常量，tsc 与构建都不会校验其内部语法：一处笔误（例如漏写逗号）
 * 就会让整块 SDK 解析失败、window.hc 永不挂载，而且运行期没有任何提示。
 *
 * 渲染进程的 CSP 是 script-src 'self' 'unsafe-inline'（不含 'unsafe-eval'），
 * new Function / eval 会被直接拦成 EvalError，所以这里改用「插入一段只解析、不执行的
 * <script>」：把源码包进一个永不调用的函数，语法错误会以 SyntaxError 形式上报到
 * window 的 error 事件，从而在不放宽 CSP 的前提下完成自检。
 */
function checkSdkSyntax(): void {
  let settled = false
  const script = document.createElement('script')
  script.textContent = `void function () {\n${SDK}\n}`

  const onError = (e: ErrorEvent): void => {
    if (settled) return
    // 只认「本文档内联脚本」的语法错误，避免把别处的运行时错误算到 SDK 头上
    if (e.filename && e.filename !== location.href) return
    if (!(e.error instanceof SyntaxError)) return
    settled = true
    window.removeEventListener('error', onError, true)
    const detail = `SDK 存在语法错误，window.hc 将不可用：${e.error.message}`
    console.error('[自定义主页]', detail)
    try {
      window.api.homepage.log('error', `[自定义主页] ${detail}`)
    } catch {
      /* 启动早期日志通道可能尚未就绪，此时仅保留控制台输出 */
    }
  }

  window.addEventListener('error', onError, true)
  ;(document.head ?? document.documentElement).appendChild(script)
  script.remove()
  // 解析失败是异步上报的：留一个短窗口后撤掉监听，避免长期占用 error 事件。
  window.setTimeout(() => {
    if (settled) return
    settled = true
    window.removeEventListener('error', onError, true)
  }, 50)
}

checkSdkSyntax()
